### ISSUE TITLE
Fix e0.predict.extra for male predictions

### ISSUE THREAD

**Issue by hanase** [PPgp/bayesLife#3]
If the male predictions (for non-extra countries) are generated using my.e0.file that includes countries not contained in the wpp e0M dataset, the e0.predict.extra (for male projections) is not doing the right thing. Check get.wpp.e0.data.for.countries.

**Comment by patrick-gerland** [comment]
Hana - This problem didn't exist when I run the 2012 revision because at
the time I followed these steps.

P.

**Comment by hanase** [comment]
Patrick, for the 2012 revision you used e0M and e0F datasets, therefore it worked. But the behavior that Igor uncovered in the particular situation is not correct. I hope the workaround works for you guys.

**Comment by patrick-gerland** [comment]
Yes, it does - thanks

Patrick - Sent from my iPhone

**Comment by hanase** [comment]
This should be fixed now.
